#!/bin/sh
# Name: testPerformance
# Project: CIFS Client
# Author: Christian Starkjohann <cs@obdev.at>
# Creation Date: 1998-05-16
# Tabsize: 4
# Copyright: (c) 1998 by Christian Starkjohann. This program is distributed
#     under the terms of the Gnu General Public License (GPL).
# 
# Copyright © 2009 Apple Inc.  
# This program is free software; you can redistribute it and/or modify it 
# under the terms of the GNU General Public License version 2 only.  This 
# program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied WARRANTY OF MERCHANTABILITY OR 
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
# version 2 for more details.  A copy of the GNU General Public License 
# version 2 is included along with this program.
# 
# General Description:
# This script runs some performance tests within a given directory of the
# file system.

mypath=`pwd`

PATH=$PATH:/etc:/usr/ucb     # extend search path

srvdir="$1"

testLarge=/bin/true
testMany=/bin/true

if [ -z "$srvdir" ]; then
	echo "You need to specify a destination directory"
	echo "Usage: $0 <directory-to-test>"
	exit 1
fi

if [ -r "$srvdir" ]; then
	deletesrv=no
else
	if mkdir "$srvdir"; then
		true
	else
		echo "error creating test directory"
		exit 1
	fi
	deletesrv=yes
fi

tmpdir="/tmp/testperf-`whoami`-$$"

many="$tmpdir/many"
large="$tmpdir/large"

mkdir "$tmpdir"
mkdir "$many"

if $testLarge; then
	echo "Setting up large file with 64MB "
	echo 123456789012345678901234567890123456789012345678901234567890123 >$large
	dd if=$large bs=64 count=1023 >>$large	# file should now be 64k
	dd if=$large bs=65536 count=1023 >>$large	# file should now be 64MB
fi

if $testMany; then
	echo -n "Setting up directory with 2000 files "
	for i in 0 1; do
		for j in 0 1 2 3 4 5 6 7 8 9; do
			for k in 0 1 2 3 4 5 6 7 8 9; do
				for l in 0 1 2 3 4 5 6 7 8 9; do
					echo "this is file $i$j$k$l" >$many/file-$i$j$k$l.txt
				done
				echo -n '.'
			done
		done
	done
fi

echo

if $testLarge; then
	echo "----------------------------------------------------------------------"
	echo "First test: copy large file to server"
	time cp $large $srvdir
	
	echo "----------------------------------------------------------------------"
	echo "Second test: copy large file from server"
	rm $large
	time cp $srvdir/large $large
	rm $srvdir/large
fi

if /$testMany; then
	echo "----------------------------------------------------------------------"
	echo "Copy 2000 files to server"
	time cp -r $many $srvdir
	
	echo "----------------------------------------------------------------------"
	echo "Copy 2000 files from server"
	rm -r $many
	time cp -r $srvdir/many $many
	
	echo "----------------------------------------------------------------------"
	echo "Disk usage of large directory"
	time du $srvdir/many
	
	echo "----------------------------------------------------------------------"
	echo "Listing of large directory"
	time ls -al $srvdir/many >/dev/null
	
	echo "----------------------------------------------------------------------"
	echo "Deleting 2000 files on server"
	time rm -r $srvdir/many
fi

echo "----------------------------------------------------------------------"
echo "cleaning up"

rm -rf "$tmpdir"
if [ $deletesrv '=' yes ]; then
	rmdir $srvdir
fi

echo "ready."
